### ISSUE TITLE
How to use with Browserify/CommonJS?

### ISSUE THREAD

**Issue by GeoffreyBooth** [ef4/ember-giftwrap#7]
I’m using Browserify with a non-CLI Ember project. I can’t seem to find a way to include the generated `addons.js` file; I’ve tried `deamdify` and other Browserify transforms, without luck. Is there something unusual about `addons.js` that would make it incompatible with CommonJS and AMD/`deamdify`? Is there some way to generate addons.js without the module wrappers? Any advice to point me in the right direction would be appreciated.

**Comment by ef4** [comment]
I don't know why it couldn't be made to work. How does it fail?

If browserify is trying to process the `requires` inside addons.js, you can use browserifies `noparse` to make it ignore them (and also probably get a faster build).
